name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: cmake
      run: cmake .
    - name: make
      run: make
    - name: test-all-executables
      run: |
          ./map-linux/build/test-map-linux
          ./map-jemalloc/build/test-map-jemalloc
          ./map-linux/build/bench-map-linux
          ./map-jemalloc/build/bench-map-jemalloc
